/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/damages` | `/damages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/duration` | `/duration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/event/new`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/event/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/damages` | `/damages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/duration` | `/duration`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recommendations` | `/recommendations`; params?: Router.UnknownOutputParams; } | { pathname: `/event/new`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/event/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/event/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/damages${`?${string}` | `#${string}` | ''}` | `/damages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/duration${`?${string}` | `#${string}` | ''}` | `/duration${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/location${`?${string}` | `#${string}` | ''}` | `/location${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recommendations${`?${string}` | `#${string}` | ''}` | `/recommendations${`?${string}` | `#${string}` | ''}` | `/event/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/damages` | `/damages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/duration` | `/duration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recommendations` | `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/event/new`; params?: Router.UnknownInputParams; } | `/+not-found` | `/event/${Router.SingleRoutePart<T>}` | `/event/edit/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/event/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
